# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "norgeskart3"
  tags:
  - "public"
spec:
  type: "website"
  lifecycle: "production"
  owner: "team_norgeskart_og_topo"
  system: "norgeskart"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "norgeskart3"
  links:
  - url: "https://github.com/kartverket/norgeskart3"
    title: "norgeskart3 på GitHub"
spec:
  type: "repo"
  owner: "team_norgeskart_og_topo"
  dependencyOf:
  - "component:norgeskart3"
