angular.module('isyTranslate').constant('translations', {
  no: {
    "AcceptAndContinue": "FORSTÅR OG AKSEPTERER",
    "AddLegend": "TA MED TEGNFORKLARING",
    "AddSweden": "TA MED DATA I SVERIGE (INNTIL 50 KM)",
    "Adresse": "Adresse",
    "Ansvar": "BRUKERENS ANSVAR",
    "Back": "< TILBAKE",
    "Cancel_txt": "AVBRYT",
    "CorrectRoad": "ER DETTE RIKTIG?",
    "Dekning_title": "Kartbladoversikt",
    "DownloadMap": "LAST NED KART",
    "Draw_title": "Tegne",
    "ED50": "ED50 - Geografiske grader",
    "ED50_UTM_31": "ED50, UTM-sone 31",
    "ED50_UTM_32": "ED50, UTM-sone 32",
    "ED50_UTM_33": "ED50, UTM-sone 33",
    "ED50_UTM_34": "ED50, UTM-sone 34",
    "ED50_UTM_35": "ED50, UTM-sone 35",
    "ED50_UTM_36": "ED50, UTM-sone 36",
    "EU89_Lat_Lon": "EU89 - Geografiske grader (Lat/Lon)",
    "EU89_UTM_31": "EU89, UTM-sone 31",
    "EU89_UTM_32": "EU89, UTM-sone 32",
    "EU89_UTM_33": "EU89, UTM-sone 33",
    "EU89_UTM_34": "EU89, UTM-sone 34",
    "EU89_UTM_35": "EU89, UTM-sone 35",
    "EU89_UTM_36": "EU89, UTM-sone 36",
    "Fargeleggingskart_info": "Dra i kartet slik at det gule feltet dekker området du vil skrive ut.",
    "Fargeleggingskart_navn": "GI KARTET DITT ET NAVN: ",
    "Fargeleggingskart_navn_eks": "Fargeleggingskartnavn",
    "Fargeleggingskart_title": "FARGELEGGINGSKART",
    "Fastmerker_title": "Fastmerker",
    "FoundRoadIs": "FUNNET VEI ER:",
    "FremhevMerkedeStier": "FREMHEV MERKEDE STIER",
    "Friluft_title": "Friluft",
    "Geografisk koordinat": "Geografisk koordinat",
    "GiPunktetNavn": "GI PUNKTET DITT ET NAVN:",
    "Gårds og bruksnummer": "Gårds- og bruksnummer",
    "HeightEstimatedByInterpolation_text": "Høyde (anslått ved interpolering): ",
    "HereYouFind_text": "HER FINNER DU: ",
    "In": "i",
    "Large": "L",
    "Luftfartshindre_title": "Luftfartshindre",
    "MeasureLine_title": "Mål lengde",
    "Measure_title": "Mål areal",
    "Medium": "M",
    "MetersAboveSeaLevel": "moh",
    "Municipality": "kommune",
    "NGO1948_GaussK_1": "NGO1948, Gauss-K. Akse 1",
    "NGO1948_GaussK_2": "NGO1948, Gauss-K. Akse 2",
    "NGO1948_GaussK_3": "NGO1948, Gauss-K. Akse 3",
    "NGO1948_GaussK_4": "NGO1948, Gauss-K. Akse 4",
    "NGO1948_GaussK_5": "NGO1948, Gauss-K. Akse 5",
    "NGO1948_GaussK_6": "NGO1948, Gauss-K. Akse 6",
    "NGO1948_GaussK_7": "NGO1948, Gauss-K. Akse 7",
    "NGO1948_GaussK_8": "NGO1948, Gauss-K. Akse 8",
    "Next": "FORTSETT >",
    "Nodplakat": "Nødplakat",
    "NodplakatText1": "Nødplakaten er utviklet i samarbeid med Hovedredningsentralene og nødetatene. Kartverket er ansvarlig for datagrunnlaget, dvs. stedsnavn og kart - samt teknologien bak.",
    "NodplakatText2": "Det er brukerens ansvar å kontrollere at det er korrekt hytte eller sted som vises på plakaten.",
    "NodplakatText3": "Kartverket tar ikke ansvar for mulige feil som skyldes brukeren, datagrunnlaget eller teknologien.",
    "PlaceIs": "STEDET ER:",
    "Scale": "Målestokk",
    "Small": "S",
    "Stedsnavn": "Stedsnavn",
    "Stedsnavn_title": "Stedsnavn",
    "Tilgjengelighet_title": "Tilgjengelighet",
    "TransformCoor_title": "Transformere koordinater",
    "Turkart_info": "Flytt kartet slik at det gule feltet dekker området du ønsker å skrive ut.",
    "Turkart_navn": "GI KARTET DITT ET NAVN: ",
    "Turkart_navn_eks": "Turkartnavn",
    "Turkart_title": "MITT TURKART",
    "UTM-koordinat": "UTM-koordinat",
    "UseMapView_title": "Bruk kartutsnitt",
    "Vegnavn": "Veinavn",
    "administrative_omrader": "Administrative områder",
    "adresser": "Adresser",
    "amtskart": "Amtskart",
    "andre": "Andre",
    "andre_linjehindre": "Andre linjehindre",
    "andre_linjer_40m_60m": "Andre linjer 40m-60m",
    "andre_linjer_60m_og_over": "Andre linjer 60m og over",
    "andre_linjer_under_40m": "Andre linjer under 40 m",
    "andre_linjer_uten_hoyde": "Andre linjer uten høyde",
    "annen": "Andre turruter",
    "annen_gradering": "Andre graderte turruter",
    "annen_rute_ekspert": "Ekspert",
    "annen_rute_enkel": "Enkel",
    "annen_rute_gradering_ikke_angitt": "Gradering ikke angitt",
    "annen_rute_ingen_gradering": "Ingen gradering",
    "annen_rute_krevende": "Krevende",
    "annen_rute_middels": "Middels",
    "avslatt": "Avslått skrivemåte",
    "baderampe": "Baderampe",
    "bakgrunnskart": "Bakgrunnskart",
    "bosetning_eiendom": "Bosetning/eiendom",
    "bygninger": "Bygninger",
    "cancel": "Avbryt",
    "change_txt": "REDIGER",
    "chooseFile_txt": "VELG FIL",
    "close_txt": "LUKK",
    "collapse_txt": "SKJUL",
    "color_txt": "FARGE:",
    "copyLink_txt": "KOPIER LENKE",
    "copy_txt": "KOPIER",
    "dekning": "Dekning",
    "dele_kartet": "Dele kartet",
    "description_txt": "BESKRIVELSE (VALGFRITT)",
    "downloadEmergencyPoster": "LAST NED",
    "download_txt": "LAST NED",
    "drawInMap_txt": "TEGN I KARTET",
    "drawProfile_txt": "TEGNE HØYDEPROFIL",
    "elektron_sjokart": "Elektronisk sjøkart",
    "elevationProfile_menu": "HØYDEPROFIL",
    "email_txt": "SEND SOM E-POST",
    "embedMap_txt": "BYGG INN KART",
    "empty_txt": "TØM",
    "enkel": "Enkel",
    "expand_txt": "VIS",
    "facebook_txt": "FACEBOOK",
    "fakta": "Fakta",
    "fastmerker": "Fastmerker",
    "ferskvann": "Ferskvann",
    "fiskeplass": "Fiskeplass",
    "flybilder": "Flybilder",
    "forenklet_vedtak": "Forenklet vedtak",
    "foreslatt": "Foreslått",
    "fotrute_ekspert": "Ekspert",
    "fotrute_enkel": "Enkel",
    "fotrute_gradering": "Graderte fotruter",
    "fotrute_gradering_ikke_angitt": "Gradering ikke angitt",
    "fotrute_ingen_gradering": "Ingen gradering",
    "fotrute_krevende": "Krevende",
    "fotrute_middels": "Middels",
    "fotrute_type_ikke_angitt": "Ikke angitt",
    "fotruter": "Fotruter",
    "fotrutetype": "Fotrutetype",
    "friluft_elektrisk_rullestol": "Friluft elektrisk rullestol",
    "friluft_rullestol": "Friluft rullestol",
    "friluft_syn": "Friluft syn",
    "friluftsomrade": "Friluftsområde",
    "gapahukhytte": "Gapahukhytte",
    "gi_tilbakemelding": "Gi tilbakemelding",
    "godkjent": "Godkjent skrivemåte",
    "gradering": "Graderte fotruter",
    "gratone": "Gråtone",
    "grillbalplass": "Grillbålplass",
    "havnekart": "Havnekart",
    "hc_parkering": "HC-parkering",
    "heading_txt": "OVERSKRIFT (VALGFRITT)",
    "historikk": "Historiske kart",
    "historisk": "Historisk",
    "historisk_ferdselsrute": "Historisk ferdselsrute",
    "holding_number": "Gårdsnr.",
    "houseNr_txt": "Husnr",
    "hovedkart_sjo": "Hovedkart sjø",
    "hva_vil_du_gjore": "Hva vil du gjøre?",
    "iframe_longDesc": "Lang beskrivelse",
    "iframe_shortDesc": "Kort beskrivelse",
    "iframe_useMarker": "BRUK MARKØR",
    "inngang_bygg": "Inngang bygg",
    "internasjonalt": "Internasjonalt",
    "ja": "Ja",
    "jan_mayen": "Jan Mayen",
    "klage_vedtak_ikke_trukket_tilbake": "Klage, vedtak ikke trukket tilbake",
    "klage_vedtak_trukket_tilbake": "Klage, vedtak trukket tilbake",
    "klage_vedtak_utsatt": "Klage, vedtak utsatt",
    "kommunenes_fjelltopper": "Kommunenes fjelltopper",
    "koordTrans": "SE KOORDINATER",
    "koord_info": "Velg koordinatsystem i listen for å transformere.",
    "koord_nord": "Nord",
    "koord_ost": "Øst",
    "koord_tittel": "Koordinater",
    "koord_vis_flere": "Vis flere koordinatsystemer.",
    "kraftledning_40m_60m": "Kraftledning 40m-60m",
    "kraftledning_60m_og_over": "Kraftledning 60m og over",
    "kraftledning_under_40m": "Kraftledning under 40 m",
    "kraftledning_uten_hoyde": "Kraftledning uten høyde",
    "kraftledninger": "Kraftledninger",
    "kraftstolpe_40m_60m": "Kraftstolpe 40m-60m",
    "kraftstolpe_60m_og_over": "Kraftstolpe 60m og over",
    "kraftstolpe_under_40m": "Kraftstolpe under 40 m",
    "kraftstolpe_uten_hoyde": "Kraftstolpe uten høyde",
    "kultur": "Kultur",
    "kultursti": "Kultursti",
    "kvensk": "Kvensk",
    "kystkart": "Kystkart",
    "kyststi": "Kyststi",
    "lagFargeleggingskart": "LAG FARGELEGGINGSKART",
    "lagNodplakat": "LAG NØDPLAKAT",
    "lagTurkart": "LAG TURKART",
    "lag_hoydeprofil": "Lag høydeprofil",
    "landkart": "Landkart",
    "landsnettpunkter": "Landsnettpunkter",
    "lease_number": "Festenr.",
    "legend_txt": "Tegnforklaring",
    "lineType_txt": "LINJETYPE:",
    "line_txt": "LINJE",
    "linjepunkt_40m_60m": "Linjepunkt 40m-60m",
    "linjepunkt_60m_og_over": "Linjepunkt 60m og over",
    "linjepunkt_under_40m": "Linjepunkt under 40 m",
    "linjepunkt_uten_hoyde": "Linjepunkt uten høyde",
    "linkToEmbeddedMap_txt": "LENKE TIL INNBYGD KART",
    "login": "Logg inn",
    "logout": "Logg ut",
    "lulesamisk": "Lulesamisk",
    "markslag": "Markslag",
    "matrikkel_data": "Matrikkel-data",
    "menu": "Meny",
    "municipality_name": "Kommune",
    "municipality_number": "Kommunenr.",
    "natursti": "Natursti",
    "navnesak_reist": "Navnesak reist",
    "navnesak_vedtak": "Navnesak vedtatt",
    "navnesakstatus": "Navnesakstatus",
    "navnesakstatus_ubehandlet": "Navnesakstatus, ubehandlet",
    "navnetype": "Navnetype",
    "nei": "Nei",
    "niv_fastmerker": "Niv. fastmerker",
    "nordsamisk": "Nordsamisk",
    "norge_1_50000": "Norge 1:50000",
    "norsk": "Norsk",
    "ok_1_utgave": "Øk–1.utgave",
    "opacity_txt": "GJENNOMSIKTIGHET:",
    "overseilingskart": "Overseilingskart",
    "parkerings_omrade": "Parkeringsområde",
    "parkeringsomrader": "Parkeringsområder",
    "password": "Passord",
    "pointType_txt": "PUNKTTYPE:",
    "point_txt": "PUNKT",
    "polygon_txt": "FLATE",
    "privat": "Privat",
    "profileInfo_txt": "Klikk på steder i kartet for å tegne opp en linje. Avslutt med dobbeltklikk.",
    "property_moreResults": "Tilknyttede eiendommer",
    "punkthindre": "Punkthindre",
    "punkthindre_40m_60m": "Punkthindre 40m-60m",
    "punkthindre_60m_og_over": "Punkthindre 60m og over",
    "punkthindre_under_40m": "Punkthindre under 40 m",
    "punkthindre_uten_hoyde": "Punkthindre uten høyde",
    "rasterkart": "Rasterkart",
    "remove_txt": "SLETT",
    "ruteinfopunkt": "ruteinfopunkt",
    "samferdsel": "Samferdsel",
    "samlevedtak": "Samlevedtak",
    "samlevedtak_siste_12_mnd": "Samlevedtak siste 12 mnd",
    "samlevedtak_siste_24_mnd": "Samlevedtak siste 24 mnd",
    "samlevedtak_siste_3_mnd": "Samlevedtak siste 3 mnd",
    "samlevedtak_siste_6_mnd": "Samlevedtak siste 6 mnd",
    "samlevedtak_siste_mnd": "Samlevedtak siste mnd",
    "samlevedtak_trukket_tilbake": "Samlevedtak, trukket tilbake",
    "save_txt": "LAGRE",
    "seEiendom": "SE EIENDOMSINFORMASJON",
    "seEiendom_title": "Eiendom",
    "search": "Søk",
    "searchResult_addresses": "ADRESSER",
    "searchResult_cadastre": "EIENDOMMER",
    "searchResult_houseNumber": "Husnummer",
    "searchResult_placenames": "STEDSNAVN",
    "searchResult_roads": "VEGER",
    "search_text": "Søk i Norgeskart",
    "section_number": "Seksjonsnr.",
    "shareOnline_txt": "DEL PÅ NETTET",
    "showCoordinates_txt": "VIS KOORDINATER PÅ KARTET",
    "showElevationProfile_txt": "VIS HØYDEPROFIL",
    "showMeasurements_txt": "VIS MÅL PÅ KARTET",
    "showMoreInformation": "VIS MER INFORMASJON",
    "showSelection_txt": "MARKER EIENDOM",
    "sittegruppe": "Sittegruppe",
    "size_txt": "STØRRELSE:",
    "sjo": "Sjø",
    "sjokart": "Sjøkart",
    "skal_ikke_behandles_etter_loven": "Skal ikke behandles etter loven",
    "skiloype_ekspert": "Ekspert",
    "skiloype_enkel": "Enkel",
    "skiloype_gradering": "Graderte skiløyper",
    "skiloype_gradering_ikke_angitt": "Gradering ikke angitt",
    "skiloype_ingen_gradering": "Ingen gradering",
    "skiloype_krevende": "Krevende",
    "skiloype_middels": "Middels",
    "skiloyper": "Skiløyper",
    "skriv_ut": "Skriv ut",
    "skrivematestatus": "Skrivemåtestatus",
    "snap_txt": "SNAP",
    "sorsamisk": "Sørsamisk",
    "sprak": "Språk",
    "ssrFakta": "SE FAKTA OM STEDSNAVNET",
    "stamnettpunkter": "Stamnettpunkter",
    "statlig_sikret": "Statlig sikra",
    "subholding_number": "Bruksnr.",
    "svalbard": "Svalbard",
    "sykkel_gradering": "Graderte sykkelruter",
    "sykkelrute_ekspert": "Ekspert",
    "sykkelrute_enkel": "Enkel",
    "sykkelrute_gradering_ikke_angitt": "Gradering ikke angitt",
    "sykkelrute_ingen_gradering": "Ingen gradering",
    "sykkelrute_krevende": "Krevende",
    "sykkelrute_middels": "Middels",
    "sykkelruter": "Sykkelruter",
    "tegne_og_male": "Tegne og måle",
    "teiger_og_grenser": "Teiger og grenser",
    "temakart": "Temakart",
    "terreng": "Terreng",
    "terrengformer": "Terrengformer",
    "tettsted_elektrisk_rullestol": "Tettsted elektrisk rullestol",
    "tettsted_rullestol": "Tettsted rullestol",
    "tettsted_syn": "Tettsted syn",
    "text_txt": "TEKST",
    "text_txt_label": "TEKST:",
    "tips_og_triks": "Tips og triks",
    "toalett": "Toalett",
    "trekantpunkter": "Trekantpunkter",
    "trimloype": "Trimløype",
    "tur_og_friluftsruter": "Tur- og friluftsruter",
    "turisthytte": "Turisthytte",
    "turvei": "Turvei",
    "twitter_txt": "TWITTER",
    "ubehandlet": "Navnesaksstatus ubehandlet",
    "uploadFile_txt": "LAST OPP FIL",
    "username": "Brukernavn",
    "utm_rutenett": "UTM-rutenett",
    "uvurdert": "Uvurdert skrivemåte",
    "vedtak": "Vedtak siste periode",
    "vedtak_siste_12_mnd": "Vedtak siste 12 mnd",
    "vedtak_siste_24_mnd": "Vedtak siste 24 mnd",
    "vedtak_siste_3_mnd": "Vedtak siste 3 mnd",
    "vedtak_siste_6_mnd": "Vedtak siste 6 mnd",
    "vedtak_siste_mnd": "Vedtak siste mnd",
    "vedtak_utsatt": "Vedtak utsatt",
    "vedtatt": "Vedtatt",
    "vedtatt_av_navnemyndighet": "Navnevalg vedtatt av navnemyndighet",
    "vedtatt_navneledd": "Vedtatt navneledd",
    "vei": "Vei",
    "width_txt": "TYKKELSE:"
  },
  nn: {
    "AcceptAndContinue": "EG SKJØNAR OG GODTAR",
    "AddLegend": "TA MED TEIKNFORKLARING",
    "AddSweden": "TA MED DATA I SVERIGE (INNTIL 50 KM)",
    "Adresse": "Adresse",
    "Ansvar": "BRUKARENS ANSVAR",
    "Back": "< TILBAKE",
    "Cancel_txt": "AVBRYT",
    "CorrectRoad": "ER DETTE RETT?",
    "Dekning_title": "Kartbladoversikt",
    "DownloadMap": "LAST NED KART",
    "Draw_title": "Teikne",
    "ED50": "ED50 - Geografiske grader",
    "ED50_UTM_31": "ED50, UTM-sone 31",
    "ED50_UTM_32": "ED50, UTM-sone 32",
    "ED50_UTM_33": "ED50, UTM-sone 33",
    "ED50_UTM_34": "ED50, UTM-sone 34",
    "ED50_UTM_35": "ED50, UTM-sone 35",
    "ED50_UTM_36": "ED50, UTM-sone 36",
    "EU89_Lat_Lon": "EU89 - Geografiske grader (Lat/Lon)",
    "EU89_UTM_31": "EU89, UTM-sone 31",
    "EU89_UTM_32": "EU89, UTM-sone 32",
    "EU89_UTM_33": "EU89, UTM-sone 33",
    "EU89_UTM_34": "EU89, UTM-sone 34",
    "EU89_UTM_35": "EU89, UTM-sone 35",
    "EU89_UTM_36": "EU89, UTM-sone 36",
    "Fargeleggingskart_info": "Dra i kartet slik at det gule feltet dekkjer området du vil skrive ut.",
    "Fargeleggingskart_navn": "GI KARTET DITT EIT NAMN: ",
    "Fargeleggingskart_navn_eks": "Fargeleggingskartnamn",
    "Fargeleggingskart_title": "FARGELEGGINGSKART",
    "Fastmerker_title": "Fastmerke",
    "FoundRoadIs": "FUNNEN VEG ER:",
    "FremhevMerkedeStier": "FRAMHEV MERKA STIGAR",
    "Friluft_title": "Friluft",
    "Geografisk koordinat": "Geografisk koordinat",
    "GiPunktetNavn": "GI PUNKTET DITT EIT NAMN:",
    "Gårds og bruksnummer": "Gards- og bruksnummer",
    "HeightEstimatedByInterpolation_text": "Høgde (anslått ved interpolering): ",
    "HereYouFind_text": "HER FINN DU: ",
    "In": "i",
    "Large": "L",
    "Luftfartshindre_title": "Luftfartshinder",
    "MeasureLine_title": "Mål lengde",
    "Measure_title": "Mål areal",
    "Medium": "M",
    "MetersAboveSeaLevel": "moh",
    "Municipality": "kommune",
    "NGO1948_GaussK_1": "NGO1948, Gauss-K. Akse 1",
    "NGO1948_GaussK_2": "NGO1948, Gauss-K. Akse 2",
    "NGO1948_GaussK_3": "NGO1948, Gauss-K. Akse 3",
    "NGO1948_GaussK_4": "NGO1948, Gauss-K. Akse 4",
    "NGO1948_GaussK_5": "NGO1948, Gauss-K. Akse 5",
    "NGO1948_GaussK_6": "NGO1948, Gauss-K. Akse 6",
    "NGO1948_GaussK_7": "NGO1948, Gauss-K. Akse 7",
    "NGO1948_GaussK_8": "NGO1948, Gauss-K. Akse 8",
    "Next": "FORTSET >",
    "Nodplakat": "Nødplakat",
    "NodplakatText1": "Nødplakaten er utvikla i samarbeid med Hovudredningsentralane og nødetatane. Kartverket er ansvarleg for datagrunnlaget, dvs. stadnamn og kart - samt teknologien bak.",
    "NodplakatText2": "Brukaren har ansvar å kontrollere at det er korrekt hytte eller stad som blir vist på plakaten.",
    "NodplakatText3": "Kartverket tar ikkje ansvar for moglege feil som skuldast brukaren, datagrunnlaget eller teknologien.",
    "PlaceIs": "STADEN ER:",
    "Scale": "Målestokk",
    "Small": "S",
    "Stedsnavn": "Stadnamn",
    "Stedsnavn_title": "Stadnamn",
    "Tilgjengelighet_title": "Tilgjenge",
    "TransformCoor_title": "Transformere koordinatar",
    "Turkart_info": "Flytt kartet slik at det gule feltet dekkjer området du ynskjer å skrive ut.",
    "Turkart_navn": "GI KARTET DITT EIT NAMN: ",
    "Turkart_navn_eks": "Turkartnamn",
    "Turkart_title": "MITT TURKART",
    "UTM-koordinat": "UTM-koordinat",
    "UseMapView_title": "Bruk kartutsnitt",
    "Vegnavn": "Vegnamn",
    "administrative_omrader": "Administrative område",
    "adresser": "Adresser",
    "amtskart": "Amtskart",
    "andre": "Andre",
    "andre_linjehindre": "Andre linjehinder",
    "andre_linjer_40m_60m": "Andre linjer 40m-60m",
    "andre_linjer_60m_og_over": "Andre linjer 60m og over",
    "andre_linjer_under_40m": "Andre linjer under 40 m",
    "andre_linjer_uten_hoyde": "Andre linjer utan høgde",
    "annen": "Andre turruter",
    "annen_gradering": "Andre graderte turruter",
    "annen_rute_ekspert": "Ekspert",
    "annen_rute_enkel": "Enkel",
    "annen_rute_gradering_ikke_angitt": "Gradering ikkje angitt",
    "annen_rute_ingen_gradering": "Ingen gradering",
    "annen_rute_krevende": "Krevjande",
    "annen_rute_middels": "Middels",
    "avslatt": "Avslege skrivemåte",
    "baderampe": "Baderampe",
    "bakgrunnskart": "Bakgrunnskart",
    "bosetning_eiendom": "Busetning/eigedom",
    "bygninger": "Bygningar",
    "cancel": "Avbryt",
    "change_txt": "REDIGER",
    "chooseFile_txt": "VEL FIL",
    "close_txt": "LUKK",
    "collapse_txt": "SKJUL",
    "color_txt": "FARGE:",
    "copyLink_txt": "KOPIER LENKE",
    "copy_txt": "KOPIER",
    "dekning": "Dekning",
    "dele_kartet": "Dele kartet",
    "description_txt": "KORT INFORMASJONSTEKST (VALFRITT)",
    "downloadEmergencyPoster": "LAST NED",
    "download_txt": "LAST NED",
    "drawInMap_txt": "TEIKN I KARTET",
    "drawProfile_txt": "TEIKNE HØGDEPROFIL",
    "elektron_sjokart": "Elektronisk sjøkart",
    "elevationProfile_menu": "HØGDEPROFIL",
    "email_txt": "SEND SOM E-POST",
    "embedMap_txt": "BYGG INN KART",
    "empty_txt": "TØM",
    "enkel": "Enkel",
    "expand_txt": "VIS",
    "facebook_txt": "FACEBOOK",
    "fakta": "Fakta",
    "fastmerker": "Fastmerke",
    "ferskvann": "Ferskvatn",
    "fiskeplass": "Fiskeplass",
    "flybilder": "Flybilete",
    "forenklet_vedtak": "Forenkla vedtak",
    "foreslatt": "Foreslått",
    "fotrute_ekspert": "Ekspert",
    "fotrute_enkel": "Enkel",
    "fotrute_gradering": "Graderte fotruter",
    "fotrute_gradering_ikke_angitt": "Gradering ikkje angitt",
    "fotrute_ingen_gradering": "Ingen gradering",
    "fotrute_krevende": "Krevjande",
    "fotrute_middels": "Middels",
    "fotrute_type_ikke_angitt": "Ikkje angitt",
    "fotruter": "Fotruter",
    "fotrutetype": "Fotrutetype",
    "friluft_elektrisk_rullestol": "Friluft elektrisk rullestol",
    "friluft_rullestol": "Friluft rullestol",
    "friluft_syn": "Friluft syn",
    "friluftsomrade": "Friluftsområde",
    "gapahukhytte": "Gapahukhytte",
    "gi_tilbakemelding": "Gi tilbakemelding",
    "godkjent": "Godkjend skrivemåte",
    "gradering": "Graderte fotruter",
    "gratone": "Gråtone",
    "grillbalplass": "Grillbålplass",
    "havnekart": "Havnekart",
    "hc_parkering": "HC-parkering",
    "heading_txt": "OVERSKRIFT (VALFRITT)",
    "historikk": "Historiske kart",
    "historisk": "Historisk",
    "historisk_ferdselsrute": "Historisk ferdselsrute",
    "holding_number": "Gardsnr.",
    "houseNr_txt": "Husnr",
    "hovedkart_sjo": "Hovudkart sjø",
    "hva_vil_du_gjore": "Kva vil du gjere?",
    "iframe_longDesc": "Lang informasjonstekst",
    "iframe_shortDesc": "Kort informasjonstekst",
    "iframe_useMarker": "BRUK MARKØR",
    "inngang_bygg": "Inngang bygg",
    "internasjonalt": "Internasjonalt",
    "ja": "Ja",
    "jan_mayen": "Jan Mayen",
    "klage_vedtak_ikke_trukket_tilbake": "Klage, vedtak ikkje trekt tilbake",
    "klage_vedtak_trukket_tilbake": "Klage, vedtak trekt tilbake",
    "klage_vedtak_utsatt": "Klage, vedtak utsett",
    "kommunenes_fjelltopper": "Kommunanes fjelltoppar",
    "koordTrans": "SJÅ KOORDINATAR",
    "koord_info": "Vel koordinatsystem i lista for å transformere.",
    "koord_nord": "Nord",
    "koord_ost": "Aust",
    "koord_tittel": "Koordinatar",
    "koord_vis_flere": "Vis fleire koordinatsystem.",
    "kraftledning_40m_60m": "Kraftleidning 40m-60m",
    "kraftledning_60m_og_over": "Kraftleidning 60m og over",
    "kraftledning_under_40m": "Kraftleidning under 40 m",
    "kraftledning_uten_hoyde": "Kraftleidning uten høgde",
    "kraftledninger": "Kraftleidningar",
    "kraftstolpe_40m_60m": "Kraftstolpe 40m-60m",
    "kraftstolpe_60m_og_over": "Kraftstolpe 60m og over",
    "kraftstolpe_under_40m": "Kraftstolpe under 40 m",
    "kraftstolpe_uten_hoyde": "Kraftstolpe utan høgde",
    "kultur": "Kultur",
    "kultursti": "Kultursti",
    "kvensk": "Kvensk",
    "kystkart": "Kystkart",
    "kyststi": "Kyststi",
    "lagFargeleggingskart": "LAG FARGELEGGINGSKART",
    "lagNodplakat": "LAG NØDPLAKAT",
    "lagTurkart": "LAG TURKART",
    "lag_hoydeprofil": "Lag høgdeprofil",
    "landkart": "Landkart",
    "landsnettpunkter": "Landsnettpunkt",
    "lease_number": "Festenr.",
    "legend_txt": "Teiknforklaring",
    "lineType_txt": "LINJETYPE:",
    "line_txt": "LINE",
    "linjepunkt_40m_60m": "Linjepunkt 40m-60m",
    "linjepunkt_60m_og_over": "Linjepunkt 60m og over",
    "linjepunkt_under_40m": "Linjepunkt under 40 m",
    "linjepunkt_uten_hoyde": "Linjepunkt utan høgde",
    "linkToEmbeddedMap_txt": "LENKE TIL INNBYGD KART",
    "login": "Logg inn",
    "logout": "Logg ut",
    "lulesamisk": "Lulesamisk",
    "markslag": "Markslag",
    "matrikkel_data": "Matrikkel data",
    "menu": "Meny",
    "municipality_name": "Kommune",
    "municipality_number": "Kommunenr.",
    "natursti": "Natursti",
    "navnesak_reist": "Namnesak reist",
    "navnesak_vedtak": "Namnesak vedteke",
    "navnesakstatus": "Namnesakstatus",
    "navnesakstatus_ubehandlet": "Namnesaksstatus uhandsama",
    "navnetype": "Namnetype",
    "nei": "Nei",
    "niv_fastmerker": "Niv. fastmerke",
    "nordsamisk": "Nordsamisk",
    "norge_1_50000": "Norge 1:50000",
    "norsk": "Norsk",
    "ok_1_utgave": "Øk–1.utgåve",
    "opacity_txt": "KOR GJENNOMSIKTIG:",
    "overseilingskart": "Oversiglingskart",
    "parkerings_omrade": "Parkeringsområde",
    "parkeringsomrader": "Parkeringsområde",
    "password": "Passord",
    "pointType_txt": "PUNKTTYPE:",
    "point_txt": "PUNKT",
    "polygon_txt": "FLATE",
    "privat": "Privat",
    "profileInfo_txt": "Klikk på stader i kartet for å teikne opp ei line. Avslutt med dobbeltklikk.",
    "property_moreResults": "Tilknytta eigedomar",
    "punkthindre": "Punkthinder",
    "punkthindre_40m_60m": "Punkthinder 40m-60m",
    "punkthindre_60m_og_over": "Punkthinder 60m og over",
    "punkthindre_under_40m": "Punkthinder under 40 m",
    "punkthindre_uten_hoyde": "Punkthinder utan høgde",
    "rasterkart": "Rasterkart",
    "remove_txt": "SLETT",
    "ruteinfopunkt": "ruteinfopunkt",
    "samferdsel": "Samferdsle",
    "samlevedtak": "Samlevedtak",
    "samlevedtak_siste_12_mnd": "Samlevedtak siste 12 md",
    "samlevedtak_siste_24_mnd": "Samlevedtak siste 24 md",
    "samlevedtak_siste_3_mnd": "Samlevedtak siste 3 md",
    "samlevedtak_siste_6_mnd": "Samlevedtak siste 6 md",
    "samlevedtak_siste_mnd": "Samlevedtak siste md",
    "samlevedtak_trukket_tilbake": "Samlevedtak, trekt tilbake",
    "save_txt": "LAGRE",
    "seEiendom": "SJÅ EIGEDOMSINFORMASJON",
    "seEiendom_title": "Eigedom",
    "search": "Søk",
    "searchResult_addresses": "ADRESSER",
    "searchResult_cadastre": "EIGEDOMAR",
    "searchResult_houseNumber": "Husnummer",
    "searchResult_placenames": "STADNAMN",
    "searchResult_roads": "VEGAR",
    "search_text": "Søk i Norgeskart",
    "section_number": "Seksjonsnr.",
    "shareOnline_txt": "DEL PÅ NETTET",
    "showCoordinates_txt": "VIS KOORDINATAR PÅ KARTET",
    "showElevationProfile_txt": "VIS HØGDEPROFIL",
    "showMeasurements_txt": "VIS MÅL PÅ KARTET",
    "showMoreInformation": "VIS MEIR INFORMASJON",
    "showSelection_txt": "MARKER EIGEDOM",
    "sittegruppe": "Sittegruppe",
    "size_txt": "STORLEIK:",
    "sjo": "Sjø",
    "sjokart": "Sjøkart",
    "skal_ikke_behandles_etter_loven": "Skal ikkje handsamast etter lova",
    "skiloype_ekspert": "Ekspert",
    "skiloype_enkel": "Enkel",
    "skiloype_gradering": "Graderte skiløyper",
    "skiloype_gradering_ikke_angitt": "Gradering ikkje angitt",
    "skiloype_ingen_gradering": "Ingen gradering",
    "skiloype_krevende": "Krevjande",
    "skiloype_middels": "Middels",
    "skiloyper": "Skiløyper",
    "skriv_ut": "Skriv ut",
    "skrivematestatus": "Skrivemåtestatus",
    "snap_txt": "SNAP",
    "sorsamisk": "Sørsamisk",
    "sprak": "Språk",
    "ssrFakta": "SJÅ FAKTA OM STADNAMNET",
    "stamnettpunkter": "Stamnettpunkt",
    "statlig_sikret": "Statleg sikra",
    "subholding_number": "Bruksnr.",
    "svalbard": "Svalbard",
    "sykkel_gradering": "Graderte sykkelruter",
    "sykkelrute_ekspert": "Ekspert",
    "sykkelrute_enkel": "Enkel",
    "sykkelrute_gradering_ikke_angitt": "Gradering ikkje angitt",
    "sykkelrute_ingen_gradering": "Ingen gradering",
    "sykkelrute_krevende": "Krevjande",
    "sykkelrute_middels": "Middels",
    "sykkelruter": "Sykkelruter",
    "tegne_og_male": "Teikne og måle",
    "teiger_og_grenser": "Teigar og grenser",
    "temakart": "Temakart",
    "terreng": "Terreng",
    "terrengformer": "Terrengformer",
    "tettsted_elektrisk_rullestol": "Tettstad elektrisk rullestol",
    "tettsted_rullestol": "Tettstad rullestol",
    "tettsted_syn": "Tettsted syn",
    "text_txt": "TEKST",
    "text_txt_label": "TEKST:",
    "tips_og_triks": "Tips og triks",
    "toalett": "Toalett",
    "trekantpunkter": "Trekantpunkt",
    "trimloype": "Trimløype",
    "tur_og_friluftsruter": "Tur- og friluftsruter",
    "turisthytte": "Turisthytte",
    "turvei": "Turveg",
    "twitter_txt": "TWITTER",
    "ubehandlet": "Namnesaksstatus uhandsama",
    "uploadFile_txt": "LAST OPP FIL",
    "username": "Brukarnamn",
    "utm_rutenett": "UTM-rutenett",
    "uvurdert": "Uvurdert skrivemåte",
    "vedtak": "Vedtak siste periode",
    "vedtak_siste_12_mnd": "Vedteke siste 12 md",
    "vedtak_siste_24_mnd": "Vedteke siste 24 md",
    "vedtak_siste_3_mnd": "Vedteke siste 3 md",
    "vedtak_siste_6_mnd": "Vedteke siste 6 md",
    "vedtak_siste_mnd": "Vedteke siste md",
    "vedtak_utsatt": "Vedtak utsett",
    "vedtatt": "Vedteke",
    "vedtatt_av_navnemyndighet": "Namneval vedteke/gjort av namnemyndet",
    "vedtatt_navneledd": "Vedteke namneledd",
    "vei": "Veg",
    "width_txt": "TJUKKLEIK:"
  },
  en: {
    "AcceptAndContinue": "ACCEPT AND CONTINUE",
    "AddLegend": "ADD LEGEND",
    "AddSweden": "INCLUDE SWEDISH DATA",
    "Adresse": "Address",
    "Ansvar": "RESPONSIBILITY",
    "Back": "< BACK",
    "Cancel_txt": "CANCEL",
    "CorrectRoad": "IS THIS CORRECT?",
    "Dekning_title": "Overview of Maps",
    "DownloadMap": "DOWNLOAD MAP",
    "Draw_title": "Draw",
    "ED50": "ED50 - Geographical degrees",
    "ED50_UTM_31": "ED50, UTM-zone 31",
    "ED50_UTM_32": "ED50, UTM-zone 32",
    "ED50_UTM_33": "ED50, UTM-zone 33",
    "ED50_UTM_34": "ED50, UTM-zone 34",
    "ED50_UTM_35": "ED50, UTM-zone 35",
    "ED50_UTM_36": "ED50, UTM-zone 36",
    "EU89_Lat_Lon": "EU89 - Geographical degrees (Lat/Lon)",
    "EU89_UTM_31": "EU89, UTM-zone 31",
    "EU89_UTM_32": "EU89, UTM-zone 32",
    "EU89_UTM_33": "EU89, UTM-zone 33",
    "EU89_UTM_34": "EU89, UTM-zone 34",
    "EU89_UTM_35": "EU89, UTM-zone 35",
    "EU89_UTM_36": "EU89, UTM-zone 36",
    "Fargeleggingskart_info": "Move the map so that the yellow area covers the area you want to print.",
    "Fargeleggingskart_navn": "GIVE YOUR MAP A NAME: ",
    "Fargeleggingskart_navn_eks": "Colouring map name",
    "Fargeleggingskart_title": "COLOURING MAP",
    "Fastmerker_title": "Reference marks",
    "FoundRoadIs": "FOUND ROAD IS",
    "FremhevMerkedeStier": "HIGHLIGHT MARKED TRAILS",
    "Friluft_title": "Outdoor life",
    "Geografisk koordinat": "Geographical coordinate",
    "GiPunktetNavn": "GIVE YOUR POINT A NAME:",
    "Gårds og bruksnummer": "Cadastral identifier",
    "HeightEstimatedByInterpolation_text": "Height (estimated by interpolation): ",
    "HereYouFind_text": "HERE YOU FIND: ",
    "In": "in",
    "Large": "L",
    "Luftfartshindre_title": "Aviation",
    "MeasureLine_title": "Measure length",
    "Measure_title": "Measure area",
    "Medium": "M",
    "MetersAboveSeaLevel": "m.a.s.l.",
    "Municipality": " municipality",
    "NGO1948_GaussK_1": "NGO1948, Gauss-K. Axis 1",
    "NGO1948_GaussK_2": "NGO1948, Gauss-K. Axis 2",
    "NGO1948_GaussK_3": "NGO1948, Gauss-K. Axis 3",
    "NGO1948_GaussK_4": "NGO1948, Gauss-K. Axis 4",
    "NGO1948_GaussK_5": "NGO1948, Gauss-K. Axis 5",
    "NGO1948_GaussK_6": "NGO1948, Gauss-K. Axis 6",
    "NGO1948_GaussK_7": "NGO1948, Gauss-K. Axis 7",
    "NGO1948_GaussK_8": "NGO1948, Gauss-K. Axis 8",
    "Next": "NEXT >",
    "Nodplakat": "Emergency poster",
    "NodplakatText1": "The emergency poster is developed in collaboration with the Joint Rescue centers and emergency services. Kartverket is responsible for the data, ie, place names and maps - as well as the technology.",
    "NodplakatText2": "It is the user's responsibility to verify that it is the correct cabin or location shown on the poster.",
    "NodplakatText3": "Kartverket assumes no responsibility for any errors caused by user, data or technology.",
    "PlaceIs": "THE PLACE IS:",
    "Scale": "Scale",
    "Small": "S",
    "Stedsnavn": "Place name",
    "Stedsnavn_title": "Placenames",
    "Tilgjengelighet_title": "Availability",
    "TransformCoor_title": "Transform coordinates",
    "Turkart_info": "Move the map so that the yellow area covers the area you want to print.",
    "Turkart_navn": "GIVE YOUR MAP A NAME: ",
    "Turkart_navn_eks": "Hiking map name",
    "Turkart_title": "MY HIKING MAP",
    "UTM-koordinat": "UTM-coordinate",
    "UseMapView_title": "Use map view",
    "Vegnavn": "Road name",
    "administrative_omrader": "Administrative units",
    "adresser": "Addresses",
    "amtskart": "Amtskart",
    "andre": "Other",
    "andre_linjehindre": "Other line obstacles",
    "andre_linjer_40m_60m": "Other line obstacles 40m-60m",
    "andre_linjer_60m_og_over": "Other line obstacles 60m and above",
    "andre_linjer_under_40m": "Other line obstacles below 40m",
    "andre_linjer_uten_hoyde": "Other line obstacles without height",
    "annen": "Other routes",
    "annen_gradering": "Other routes with degree of difficulty",
    "annen_rute_ekspert": "Expert only",
    "annen_rute_enkel": "Easy",
    "annen_rute_gradering_ikke_angitt": "Degree of difficulty not specified",
    "annen_rute_ingen_gradering": "No degree of difficulty",
    "annen_rute_krevende": "Advanced",
    "annen_rute_middels": "Intermediat",
    "avslatt": "Spelling denied ",
    "baderampe": "Bathing ramp",
    "bakgrunnskart": "Base map layer",
    "bosetning_eiendom": "Settlement/property",
    "bygninger": "Buildings",
    "cancel": "Cancel",
    "change_txt": "EDIT",
    "chooseFile_txt": "CHOOSE FILE",
    "close_txt": "CLOSE",
    "collapse_txt": "HIDE",
    "color_txt": "COLOR:",
    "copyLink_txt": "COPY LINK",
    "copy_txt": "COPY",
    "dekning": "Coverage",
    "dele_kartet": "Share map",
    "description_txt": "DESCRIPTION (OPTIONAL)",
    "downloadEmergencyPoster": "DOWNLOAD",
    "download_txt": "DOWNLOAD",
    "drawInMap_txt": "DRAW IN THE MAP",
    "drawProfile_txt": "DRAW ELEVATION PROFILE",
    "elektron_sjokart": "Electronic Nautical Charts",
    "elevationProfile_menu": "ELEVATION PROFILE",
    "email_txt": "SEND AS E-MAIL",
    "embedMap_txt": "EMBED MAP",
    "empty_txt": "EMPTY",
    "enkel": "Simplified",
    "expand_txt": "SHOW",
    "facebook_txt": "FACEBOOK",
    "fakta": "Facts",
    "fastmerker": "Geodetic reference points",
    "ferskvann": "Fresh water",
    "fiskeplass": "Fishing spot",
    "flybilder": "Aerial images",
    "forenklet_vedtak": "Simplified descicion",
    "foreslatt": "Proposed",
    "fotrute_ekspert": "Expert only",
    "fotrute_enkel": "Easy",
    "fotrute_gradering": "Hiking route with degree of difficulty",
    "fotrute_gradering_ikke_angitt": "Degree of difficulty not specified",
    "fotrute_ingen_gradering": "No degree of difficulty",
    "fotrute_krevende": "Advanced",
    "fotrute_middels": "Intermediat",
    "fotrute_type_ikke_angitt": "Degree of difficulty not specified",
    "fotruter": "Hiking routes",
    "fotrutetype": "Type of special walking routes",
    "friluft_elektrisk_rullestol": "Recreation electric wheelchair",
    "friluft_rullestol": "Recreation wheelchair",
    "friluft_syn": "Recreation sight",
    "friluftsomrade": "Recreational area",
    "gapahukhytte": "Shelter",
    "gi_tilbakemelding": "Give feedback",
    "godkjent": "Spelling approved",
    "gradering": "Hiking trails with degree of difficulty",
    "gratone": "Grey scale map",
    "grillbalplass": "Barbecue bonfire",
    "havnekart": "Harbour Charts",
    "hc_parkering": "HC parking",
    "heading_txt": "HEADER (OPTIONAL)",
    "historikk": "Historical maps",
    "historisk": "Historical",
    "historisk_ferdselsrute": "Ancient trail",
    "holding_number": "Holding nr.",
    "houseNr_txt": "House nr.",
    "hovedkart_sjo": "Main Charts",
    "hva_vil_du_gjore": "What do you want to do?",
    "iframe_longDesc": "Long description",
    "iframe_shortDesc": "Short description",
    "iframe_useMarker": "USE MARKER",
    "inngang_bygg": "Building access",
    "internasjonalt": "International",
    "ja": "Yes",
    "jan_mayen": "Jan Mayen",
    "klage_vedtak_ikke_trukket_tilbake": "Appealed, descition not withdrawn",
    "klage_vedtak_trukket_tilbake": "Appealed, descition withdrawn",
    "klage_vedtak_utsatt": "Appealed, descision postponed",
    "kommunenes_fjelltopper": "Mountain tops by municipality",
    "koordTrans": "SEE COORDINATES",
    "koord_info": "Choose a coordinate system from the list to transform.",
    "koord_nord": "North",
    "koord_ost": "East",
    "koord_tittel": "Coordinates",
    "koord_vis_flere": "Show advanced coordinate systems.",
    "kraftledning_40m_60m": "Power line 40m-60m",
    "kraftledning_60m_og_over": "Power line 60m and above",
    "kraftledning_under_40m": "Power line below 40 m",
    "kraftledning_uten_hoyde": "Power line without height",
    "kraftledninger": "Power lines",
    "kraftstolpe_40m_60m": "Power line mast 40m-60m",
    "kraftstolpe_60m_og_over": "Power line mast 60m and above",
    "kraftstolpe_under_40m": "Power line mast below 40m",
    "kraftstolpe_uten_hoyde": "Power line mast without height",
    "kultur": "Culture",
    "kultursti": "Herritage path",
    "kvensk": "Kven",
    "kystkart": "Coastal Charts",
    "kyststi": "Costal trail",
    "lagFargeleggingskart": "MAKE COLOURING MAP",
    "lagNodplakat": "MAKE EMERGENCY POSTER",
    "lagTurkart": "MAKE MAP",
    "lag_hoydeprofil": "Elevation profile",
    "landkart": "Topographic map",
    "landsnettpunkter": "Geodetic control points - Landsnett",
    "lease_number": "Lease nr.",
    "legend_txt": "Legend",
    "lineType_txt": "LINE TYPE:",
    "line_txt": "LINE",
    "linjepunkt_40m_60m": "Line point 40m-60m",
    "linjepunkt_60m_og_over": "Line point 60m and above",
    "linjepunkt_under_40m": "Line point below 40m",
    "linjepunkt_uten_hoyde": "Line point without height",
    "linkToEmbeddedMap_txt": "LINK TO EMBEDDED MAP",
    "login": "Log in",
    "logout": "Logout",
    "lulesamisk": "Lule Sami",
    "markslag": "Type of land",
    "matrikkel_data": "Cadastre data",
    "menu": "Menu",
    "municipality_name": "Municipality",
    "municipality_number": "Municipality nr.",
    "natursti": "Educational path",
    "navnesak_reist": "Place name issue proposed",
    "navnesak_vedtak": "Place name issue discided",
    "navnesakstatus": "Place name status",
    "navnesakstatus_ubehandlet": "Name place issue not descided",
    "navnetype": "Name type",
    "nei": "No",
    "niv_fastmerker": "Levelling benchmarks",
    "nordsamisk": "Northern Sami",
    "norge_1_50000": "Norway 1:50000",
    "norsk": "Norwegian",
    "ok_1_utgave": "Economic chart 1. Edition",
    "opacity_txt": "TRANSPARENCY:",
    "overseilingskart": "General Charts",
    "parkerings_omrade": "Parking area",
    "parkeringsomrader": "Parking areas",
    "password": "Password",
    "pointType_txt": "POINT TYPE:",
    "point_txt": "POINT",
    "polygon_txt": "POLYGON",
    "privat": "Private",
    "profileInfo_txt": "Click in the map and start draw the line. Finish drawing by double click.",
    "property_moreResults": "Associated properties",
    "punkthindre": "Point obstacle",
    "punkthindre_40m_60m": "Point obstacle 40m-60m",
    "punkthindre_60m_og_over": "Point obstacle 60m and above",
    "punkthindre_under_40m": "Point obstacle below 40 m",
    "punkthindre_uten_hoyde": "Point obstacle without height",
    "rasterkart": "Raster map",
    "remove_txt": "DELETE",
    "ruteinfopunkt": "ruteinfopunkt",
    "samferdsel": "Transport",
    "samlevedtak": "Collective decisions",
    "samlevedtak_siste_12_mnd": "Collective decisions last 12 mths",
    "samlevedtak_siste_24_mnd": "Collective decisions last 24 mths",
    "samlevedtak_siste_3_mnd": "Collective decisions last 3 mths",
    "samlevedtak_siste_6_mnd": "Collective decisions last 6 mths",
    "samlevedtak_siste_mnd": "Collective decisions last month",
    "samlevedtak_trukket_tilbake": "Collective decisions withdrawn",
    "save_txt": "SAVE",
    "seEiendom": "SEE PROPERTY INFORMASJON",
    "seEiendom_title": "Property",
    "search": "Search",
    "searchResult_addresses": "ADDRESSES",
    "searchResult_cadastre": "PROPERTIES",
    "searchResult_houseNumber": "Housenumber",
    "searchResult_placenames": "PLACENAMES",
    "searchResult_roads": "ROADS",
    "search_text": "Search Norgeskart",
    "section_number": "Section nr.",
    "shareOnline_txt": "SHARE ONLINE",
    "showCoordinates_txt": "SHOW COORDINATES ON THE MAP",
    "showElevationProfile_txt": "SHOW ELEVATION PROFILE",
    "showMeasurements_txt": "SHOW MEASUREMENTS",
    "showMoreInformation": "SHOW MORE INFORMATION",
    "showSelection_txt": "SHOW SELECTION",
    "sittegruppe": "Seating",
    "size_txt": "SIZE:",
    "sjo": "Nautical",
    "sjokart": "Nautical Charts",
    "skal_ikke_behandles_etter_loven": "Not to be descided by law",
    "skiloype_ekspert": "Expert only",
    "skiloype_enkel": "Easy",
    "skiloype_gradering": "Ski trails with degree of difficulty",
    "skiloype_gradering_ikke_angitt": "Degree of difficulty not specified",
    "skiloype_ingen_gradering": "No degree of difficulty",
    "skiloype_krevende": "Advanced",
    "skiloype_middels": "Intermediate",
    "skiloyper": "Skiing routes",
    "skriv_ut": "Print",
    "skrivematestatus": "Spelling status",
    "snap_txt": "SNAP",
    "sorsamisk": "Southern Sami",
    "sprak": "Language",
    "ssrFakta": "SEE FACTS ABOUT PLACENAME",
    "stamnettpunkter": "Geodetic control points - Stamnett",
    "statlig_sikret": "Government secured",
    "subholding_number": "Subholding nr.",
    "svalbard": "Svalbard",
    "sykkel_gradering": "Bicycle routes with degree of difficulty",
    "sykkelrute_ekspert": "Expert only",
    "sykkelrute_enkel": "Easy",
    "sykkelrute_gradering_ikke_angitt": "Degree of difficulty not specified",
    "sykkelrute_ingen_gradering": "No degree of difficulty",
    "sykkelrute_krevende": "Advanced",
    "sykkelrute_middels": "Intermediate",
    "sykkelruter": "Bike route",
    "tegne_og_male": "Draw and measure",
    "teiger_og_grenser": "Properties and borders",
    "temakart": "Thematic map",
    "terreng": "Terrain",
    "terrengformer": "Terrain forms",
    "tettsted_elektrisk_rullestol": "Village electric wheelchair",
    "tettsted_rullestol": "Village wheelchair",
    "tettsted_syn": "Village sight",
    "text_txt": "TEXT",
    "text_txt_label": "TEXT:",
    "tips_og_triks": "Tips and Tricks",
    "toalett": "Toilet",
    "trekantpunkter": "Triangulation points",
    "trimloype": "Excercise trail",
    "tur_og_friluftsruter": "Hiking and outdoor recreation",
    "turisthytte": "Cabin",
    "turvei": "Walking trail",
    "twitter_txt": "TWITTER",
    "ubehandlet": "Place name status not descided",
    "uploadFile_txt": "UPLOAD FILE",
    "username": "Username",
    "utm_rutenett": "UTM-grid",
    "uvurdert": "Spelling not concidered",
    "vedtak": "Descisions",
    "vedtak_siste_12_mnd": "Descided within the last 12 mths",
    "vedtak_siste_24_mnd": "Descided within the last 24 mths",
    "vedtak_siste_3_mnd": "Descided within the last 3 mths",
    "vedtak_siste_6_mnd": "Descided within the last 6 mths",
    "vedtak_siste_mnd": "Descided within the last mth",
    "vedtak_utsatt": "Descision postponed",
    "vedtatt": "Descided",
    "vedtatt_av_navnemyndighet": "Descicion made by place name authority",
    "vedtatt_navneledd": "Place name part descided",
    "vei": "Road",
    "width_txt": "WIDTH:"
  }
});

