angular
    .module('isyTranslate')
    .constant('translations', {
        'no': {
            "search_text": "Søk i Norgeskart",
            "menu_selected_language": "Valgt språk",
            "english_txt": "Engelsk",
            "norwegian_txt": "Norsk (Bokmål)",
            "login": "Logg inn",
            "logout": "Logg ut",
            "username": "Brukernavn",
            "password": "Passord",
            "cancel": "Avbryt",
            "Friluft_title" : "Friluft",
            "Stedsnavn_title" : "Stedsnavn",
            "Tilgjengelighet_title" : "Tilgjengelighet",
            "Fastmerker_title" : "Fastmerker",
            "Luftfartshindre_title": "Luftfartshindre",
            "MeasureLine_title" : "Mål lengde",
            "Measure_title" : "Mål areal",
            "Draw_title": "Tegne",
            "TransformCoor_title" : "Transformere koordinater",
            "ShareMap_title" : "Del kartet",
            "UseMapView_title" : "Bruk kartutsnitt",
            "FAQ_title" : "Ofte stilte spørsmål",
            "menu_select_baselayer": "Bakgrunnskart",
            "MeasureAndDraw_title" : "Tegne og mål",
            "North_text": "Nord:",
            "East_text": "Øst:",
            "Coordinates_text": "Koordinater",
            "ShowAdvancedCoordinateSystems_text" : "Vis avanserte koordinatsystemer:",
            "Stedsnavn": "Stedsnavn",
            "Adresse": "Adresse",
            "Vegnavn": "Veinavn",
            "Geografisk koordinat": "Geografisk koordinat",
            "UTM-koordinat": "UTM-koordinat",
            "In": "i",
            "Municipality": " kommune",
            "HeightEstimatedByInterpolation_text": "Høyde (anslått ved interpolering): ",
            "MetersAboveSeaLevel": "moh",
            "WhatDoYouWantToDo_text": "Hva vil du gjøre?",
            "seEiendom": "Se eiendomsinformasjon for ",
            "ssrFakta": "Se fakta om stedsnavnet ",
            "koordTrans": "Se koordinater",
            "lagTurkart": "Lag turkart",
            "Turkart_title": "Turkart",
            "Turkart_info": "Flytt kartet slik at det gule feltet dekker området du ønsker å skrive ut.",
            "Scale": "Målestokk: ",
            "Turkart_navn" : "Gi kartet ditt et navn: ",
            "Turkart_navn_eks" : "Turkartnavn",
            "DownloadMap" : "Last ned kart",
            "FremhevMerkedeStier": "Fremhev merkede stier",
            "AddLegend": "Ta med tegnforklaringer",
            "lagNodplakat": "Lag nødplakat",
            "Nodplakat": "Nødplakat",
            "Ansvar" :"Ansvar",
            "NodplakatText1": "Nødplakaten er utviklet i samarbeid med Hovedredningsentralene og nødetatene. Kartverket er ansvarlig for datagrunnlaget, dvs. stedsnavn og kart - samt teknologien bak.",
            "NodplakatText2": "Det er brukerens ansvar å kontrollere at det er korrekt hytte eller sted som vises på plakaten.",
            "NodplakatText3": "Kartverket tar ikke ansvar for mulige feil som skyldes brukeren, datagrunnlaget eller teknologien.",
            "AcceptAndContinue": "Jeg godtar og går videre",
            "GiPunktetNavn": "Gi punktet ditt et navn:",
            "PlaceIs": "Stedet er",
            "FoundRoadIs": "Funnet vei er",
            "CorrectRoad": "Dette er riktig veg",
            "Next": "Neste >",
            "Back": "< Tilbake",
            "Print": "Skriv ut",

            "EU89_Lat_Lon": "EU89 - Geografiske grader (Lat/Lon)",
            "EU89_UTM_31": "EU89, UTM-sone 31",
            "EU89_UTM_32": "EU89, UTM-sone 32",
            "EU89_UTM_33": "EU89, UTM-sone 33",
            "EU89_UTM_34": "EU89, UTM-sone 34",
            "EU89_UTM_35": "EU89, UTM-sone 35",
            "EU89_UTM_36": "EU89, UTM-sone 36",
            "NGO1948_GaussK_1": "NGO1948, Gauss-K. Akse 1",
            "NGO1948_GaussK_2": "NGO1948, Gauss-K. Akse 2",
            "NGO1948_GaussK_3": "NGO1948, Gauss-K. Akse 3",
            "NGO1948_GaussK_4": "NGO1948, Gauss-K. Akse 4",
            "NGO1948_GaussK_5": "NGO1948, Gauss-K. Akse 5",
            "NGO1948_GaussK_6": "NGO1948, Gauss-K. Akse 6",
            "NGO1948_GaussK_7": "NGO1948, Gauss-K. Akse 7",
            "NGO1948_GaussK_8": "NGO1948, Gauss-K. Akse 8",
            "ED50": "ED50 - Geografiske grader",
            "ED50_UTM_31": "ED50, UTM-sone 31",
            "ED50_UTM_32": "ED50, UTM-sone 32",
            "ED50_UTM_33": "ED50, UTM-sone 33",
            "ED50_UTM_34": "ED50, UTM-sone 34",
            "ED50_UTM_35": "ED50, UTM-sone 35",
            "ED50_UTM_36": "ED50, UTM-sone 36",
            "draw_menu": "Tegne"
        },
        'en': {
            "search_text": "Search Norgeskart",
            "menu_selected_language": "Selected Language",
            "english_txt": "English",
            "norwegian_txt": "Norwegian (Bokmål)",
            "login": "Log in",
            "logout": "Logout",
            "username": "Username",
            "password": "Password",
            "cancel": "Cancel",
            "Friluft_title" : "Outdoor life",
            "Stedsnavn_title" : "Placenames",
            "Tilgjengelighet_title" : "Availability",
            "Fastmerker_title" : "Fastmerker",
            "Luftfartshindre_title": "Aviation",
            "MeasureLine_title" : "Measure length",
            "Measure_title" : "Measure area",
            "Draw_title": "Draw",
            "TransformCoor_title" : "Transform coordinates",
            "ShareMap_title" : "Share map",
            "UseMapView_title" : "Use map view",
            "FAQ_title" : "FAQ",
            "menu_select_baselayer": "Base map layer",
            "MeasureAndDraw_title" : "Measure & Draw",
            "North_text": "North:",
            "East_text": "East:",
            "Coordinates_text": "Coordinates",
            "ShowAdvancedCoordinateSystems_text" : "Show advanced coordinate systems:",
            "Stedsnavn": "Place name",
            "Adresse": "Address",
            "Vegnavn": "Road name",
            "Geografisk koordinat": "Geographical coordinate",
            "UTM-koordinat": "UTM-coordinate",
            "In": "in",
            "Municipality": " municipality",
            "HeightEstimatedByInterpolation_text": "Height (estimated by interpolation): ",
            "MetersAboveSeaLevel": "m.a.s.l.",
            "WhatDoYouWantToDo_text": "What do you want to do?",
            "seEiendom": "See property information for ",
            "ssrFakta": "Facts about the place ",
            "koordTrans": "See coordinates",
            "lagTurkart": "Make hiking map",
            "Turkart_title": "Hiking map",
            "Turkart_info": "Move the map so that the yellow area covers the area you want to print.",
            "Scale": "Scale: ",
            "Turkart_navn" : "Give your map a name: ",
            "Turkart_navn_eks" : "Hiking map name",
            "DownloadMap" : "Download map",
            "FremhevMerkedeStier": "Highlight marked trails",
            "AddLegend": "Add legend",
            "lagNodplakat": "Make emergency poster",
            "Nodplakat": "Emergency poster",
            "Ansvar" :"Responsibility",
            "NodplakatText1": "The emergency poster is developed in collaboration with the Joint Rescue centers and emergency services. Kartverket is responsible for the data, ie, place names and maps - as well as the technology.",
            "NodplakatText2": "It is the user's responsibility to verify that it is the correct cabin or location shown on the poster.",
            "NodplakatText3": "Kartverket assumes no responsibility for any errors caused by user, data or technology.",
            "AcceptAndContinue": "Accept and continue",
            "GiPunktetNavn": "Give your point a name:",
            "PlaceIs": "The place is",
            "FoundRoadIs": "Found road is",
            "CorrectRoad": "This is the correct road",
            "Next": "Next >",
            "Back": "< Back",
            "Print": "Print",

            "EU89_Lat_Lon": "EU89 - Geographical degrees (Lat/Lon)",
            "EU89_UTM_31": "EU89, UTM-zone 31",
            "EU89_UTM_32": "EU89, UTM-zone 32",
            "EU89_UTM_33": "EU89, UTM-zone 33",
            "EU89_UTM_34": "EU89, UTM-zone 34",
            "EU89_UTM_35": "EU89, UTM-zone 35",
            "EU89_UTM_36": "EU89, UTM-zone 36",
            "NGO1948_GaussK_1": "NGO1948, Gauss-K. Axis 1",
            "NGO1948_GaussK_2": "NGO1948, Gauss-K. Axis 2",
            "NGO1948_GaussK_3": "NGO1948, Gauss-K. Axis 3",
            "NGO1948_GaussK_4": "NGO1948, Gauss-K. Axis 4",
            "NGO1948_GaussK_5": "NGO1948, Gauss-K. Axis 5",
            "NGO1948_GaussK_6": "NGO1948, Gauss-K. Axis 6",
            "NGO1948_GaussK_7": "NGO1948, Gauss-K. Axis 7",
            "NGO1948_GaussK_8": "NGO1948, Gauss-K. Axis 8",
            "ED50": "ED50 - Geographical degrees",
            "ED50_UTM_31": "ED50, UTM-zone 31",
            "ED50_UTM_32": "ED50, UTM-zone 32",
            "ED50_UTM_33": "ED50, UTM-zone 33",
            "ED50_UTM_34": "ED50, UTM-zone 34",
            "ED50_UTM_35": "ED50, UTM-zone 35",
            "ED50_UTM_36": "ED50, UTM-zone 36",
            "draw_menu": "Draw"
        }
    });