angular
    .module('isyTranslate')
    .constant('translations', {
        'no': {
            "search_text": "Søk i Norgeskart",
            "menu_selected_language": "Valgt språk",
            "english_txt": "engelsk",
            "norwegian_txt": "norsk (Bokmål)",
            "login": "Logg inn",
            "logout": "Logg ut",
            "username": "Brukernavn",
            "password": "Passord",
            "cancel": "Avbryt",
            "Friluft_title" : "Friluft",
            "Stedsnavn_title" : "Stedsnavn",
            "Tilgjengelighet_title" : "Tilgjengelighet",
            "Fastmerker_title" : "Fastmerker",
            "Luftfartshindre_title": "Luftfartshindre",
            "MeasureLine_title" : "Mål lengde",
            "Measure_title" : "Mål areal",
            "Draw_title": "Tegne",
            "DrawAndMeasure_title": "TEGNE OG MÅLE",
            "TransformCoor_title" : "Transformere koordinater",
            "ShareMap_title" : "DELE KARTET",
            "UseMapView_title" : "Bruk kartutsnitt",
            "FAQ_title" : "Få svar på ofte stilte spørsmål",
            "menu_select_baselayer": "BAKGRUNNSKART:",
            "North_text": "NORD:",
            "East_text": "ØST:",
            "Coordinates_text": "KOORDINATER",
            "ShowAdvancedCoordinateSystems_text" : "VIS AVANSERTE KOORDINATSYSTEMER",
            "Stedsnavn": "Stedsnavn",
            "Adresse": "Adresse",
            "Vegnavn": "Veinavn",
            "Geografisk koordinat": "Geografisk koordinat",
            "Gårds og bruksnummer": "Gårds og bruksnummer",
            "UTM-koordinat": "UTM-koordinat",
            "In": "i",
            "Municipality": " kommune",
            "HeightEstimatedByInterpolation_text": "Høyde (anslått ved interpolering): ",
            "MetersAboveSeaLevel": "moh",
            "WhatDoYouWantToDo_text": "HVA VIL DU GJØRE?",
            "seEiendom": "SE EIENDOMSINFORMASJON",
            "ssrFakta": "SE FAKTA OM STEDSNAVNET",
            "koordTrans": "SE KOORDINATER",
            "lagTurkart": "LAG TURKART",
            "Turkart_title": "TURKART",
            "Turkart_info": "Flytt kartet slik at det gule feltet dekker området du ønsker å skrive ut.",
            "Scale": "MÅLESTOKK: ",
            "Turkart_navn" : "GI KARTET DITT ET NAVN: ",
            "Turkart_navn_eks" : "Turkartnavn",
            "DownloadMap" : "LAST NED KART",
            "FremhevMerkedeStier": "FREMHEV MERKEDE STIER",
            "AddLegend": "TA MED TEGNFORKLARINGER",
            "lagNodplakat": "LAG NØDPLAKAT",
            "Nodplakat": "Nødplakat",
            "Ansvar" :"BRUKERENS ANSVAR",
            "NodplakatText1": "Nødplakaten er utviklet i samarbeid med Hovedredningsentralene og nødetatene. Kartverket er ansvarlig for datagrunnlaget, dvs. stedsnavn og kart - samt teknologien bak.",
            "NodplakatText2": "Det er brukerens ansvar å kontrollere at det er korrekt hytte eller sted som vises på plakaten.",
            "NodplakatText3": "Kartverket tar ikke ansvar for mulige feil som skyldes brukeren, datagrunnlaget eller teknologien.",
            "AcceptAndContinue": "FORSTÅR OG AKSEPTERER",
            "GiPunktetNavn": "GI PUNKTET DITT ET NAVN:",
            "PlaceIs": "STEDET ER:",
            "FoundRoadIs": "FUNNET VEI ER:",
            "CorrectRoad": "DETTE ER RIKTIG",
            "Next": "FORTSETT >",
            "Back": "< TILBAKE",
            "Cancel_txt": "AVBRYT",
            "Print": "SKRIV UT",
            "ThematicMap_text" : "TEMAKART",
            "HeightProfile_text": "LAG HØYDEPROFIL",
            "ChangeTo_text" : "Bytt til",
            "GoToKartverket_text": "Gå til kartverket.no",
            "GiveFeedback_text": "Gi tilbakemelding",
            "HereYouFind_text": "HER FINNER DU: ",

            "EU89_Lat_Lon": "EU89 - Geografiske grader (Lat/Lon)",
            "EU89_UTM_31": "EU89, UTM-sone 31",
            "EU89_UTM_32": "EU89, UTM-sone 32",
            "EU89_UTM_33": "EU89, UTM-sone 33",
            "EU89_UTM_34": "EU89, UTM-sone 34",
            "EU89_UTM_35": "EU89, UTM-sone 35",
            "EU89_UTM_36": "EU89, UTM-sone 36",
            "NGO1948_GaussK_1": "NGO1948, Gauss-K. Akse 1",
            "NGO1948_GaussK_2": "NGO1948, Gauss-K. Akse 2",
            "NGO1948_GaussK_3": "NGO1948, Gauss-K. Akse 3",
            "NGO1948_GaussK_4": "NGO1948, Gauss-K. Akse 4",
            "NGO1948_GaussK_5": "NGO1948, Gauss-K. Akse 5",
            "NGO1948_GaussK_6": "NGO1948, Gauss-K. Akse 6",
            "NGO1948_GaussK_7": "NGO1948, Gauss-K. Akse 7",
            "NGO1948_GaussK_8": "NGO1948, Gauss-K. Akse 8",
            "ED50": "ED50 - Geografiske grader",
            "ED50_UTM_31": "ED50, UTM-sone 31",
            "ED50_UTM_32": "ED50, UTM-sone 32",
            "ED50_UTM_33": "ED50, UTM-sone 33",
            "ED50_UTM_34": "ED50, UTM-sone 34",
            "ED50_UTM_35": "ED50, UTM-sone 35",
            "ED50_UTM_36": "ED50, UTM-sone 36",
            "draw_menu": "TEGNE OG MÅLE",
            "iframe_useMarker": "BRUK MARKØR",
            "iframe_shortDesc": "Kort beskrivelse",
            "iframe_longDesc": "Lang beskrivelse",
            "searchResult_roads": "VEGER",
            "searchResult_addresses": "ADRESSER",
            "searchResult_cadastre": "EIENDOMMER",
            "searchResult_placenames": "STEDSNAVN",
            "elevationProfile_menu": "HØYDEPROFIL",
            "searchResult_houseNumber": "Husnummer",
            "houseNr_txt":"Husnr",
            "point_txt": "PUNKT",
            "line_txt": "LINJE",
            "polygon_txt": "FLATE",
            "text_txt": "TEKST",
            "text_txt_label": "TEKST:",
            "showMeasurements_txt" : "VIS MÅL PÅ KARTET",
            "showCoordinates_txt" : "VIS KOORDINATER PÅ KARTET",
            "pointType_txt": "PUNKTTYPE:",
            "size_txt": "STØRRELSE:",
            "Small": "S",
            "Medium": "M",
            "Large": "L",
            "color_txt": "FARGE:",
            "snap_txt" : "SNAP",
            "change_txt": "REDIGER",
            "remove_txt": "SLETT",
            "save_txt": "LAGRE",
            "empty_txt": "TØM",
            "lineType_txt": "LINJETYPE:",
            "width_txt": "TYKKELSE:",
            "opacity_txt": "GJENNOMSIKTIGHET:",
            "from_text": "FRA KARTVERKET",
            "collapse_txt" : "SKJUL",
            "expand_txt" : "VIS",
            "downloadEmergencyPoster" : "LAST NED",
            "faq_header_txt": "OFTE STILTE SPØRSMÅL",
            "drawInMap_txt": "TEGN I KARTET",
            "uploadFile_txt": "LAST OPP FIL",
            "profileInfo_txt": "Klikk på steder i kartet for å tegne opp en linje.",
            "drawProfile_txt": "TEGNE HØYDEPROFIL",
            "showElevationProfile_txt" : "VIS HØYDEPROFIL",
            "chooseFile_txt" : "VELG FIL",
            "shareOnline_txt" : "DELL PÅ NETTET",
            "embedMap_txt" : "BYGG INN KART",
            "facebook_txt" : "FACEBOOK",
            "twitter_txt" : "TWITTER",
            "email_txt" : "SEND SOM E-POST",
            "copyLink_txt" : "KOPIER LENKE",
            "copy_txt" : "KOPIER",
            "heading_txt" : "OVERSKRIFT (VALGFRITT)",
            "description_txt" : "BESKRIVELSE (VALGFRITT)",
            "linkToEmbeddedMap_txt": "LENK TIL INNBYGGET KARTET",
            "download_txt" : "LAST NED",
            "seEiendom_title" : "Eiendom",
            "close_txt" : "LUKK",
            "showSelection_txt" : "VIS MARKERING",
            "legend_txt" : "Tegnforklaring",
            "showMoreInformation" : "VIS MER INFORMASJON"

        },
        'en': {
            "search_text": "Search Norgeskart",
            "menu_selected_language": "Selected Language",
            "english_txt": "english",
            "norwegian_txt": "norwegian (Bokmål)",
            "login": "Log in",
            "logout": "Logout",
            "username": "Username",
            "password": "Password",
            "cancel": "Cancel",
            "Friluft_title" : "Outdoor life",
            "Stedsnavn_title" : "Placenames",
            "Tilgjengelighet_title" : "Availability",
            "Fastmerker_title" : "Reference marks",
            "Luftfartshindre_title": "Aviation",
            "MeasureLine_title" : "Measure length",
            "Measure_title" : "Measure area",
            "Draw_title": "Draw",
            "DrawAndMeasure_title": "DRAW AND MEASURE",
            "TransformCoor_title" : "Transform coordinates",
            "ShareMap_title" : "SHARE MAP",
            "UseMapView_title" : "Use map view",
            "FAQ_title" : "FAQ",
            "menu_select_baselayer": "BASE MAP LAYER:",
            "North_text": "NORTH:",
            "East_text": "EAST:",
            "Coordinates_text": "COORDINATES",
            "ShowAdvancedCoordinateSystems_text" : "SHOW ADVANCED COORDINATE SYSTEMS",
            "Stedsnavn": "Place name",
            "Adresse": "Address",
            "Vegnavn": "Road name",
            "Geografisk koordinat": "Geographical coordinate",
            "Gårds og bruksnummer": "Cadastral identifier",
            "UTM-koordinat": "UTM-coordinate",
            "In": "in",
            "Municipality": " municipality",
            "HeightEstimatedByInterpolation_text": "Height (estimated by interpolation): ",
            "MetersAboveSeaLevel": "m.a.s.l.",
            "WhatDoYouWantToDo_text": "WHAT DO YOU WANT TO DO?",
            "seEiendom": "SEE PROPERTY INFORMASJON",
            "ssrFakta": "SEE FACTS ABOUT PLACENAME",
            "koordTrans": "SEE COORDINATES",
            "lagTurkart": "MAKE MAP",
            "Turkart_title": "HIKING MAP",
            "Turkart_info": "Move the map so that the yellow area covers the area you want to print.",
            "Scale": "SCALE: ",
            "Turkart_navn" : "GIVE YOUR MAP A NAME: ",
            "Turkart_navn_eks" : "Hiking map name",
            "DownloadMap" : "DOWNLOAD MAP",
            "FremhevMerkedeStier": "HIGHLIGHT MARKED TRAILS",
            "AddLegend": "ADD LEGEND",
            "lagNodplakat": "MAKE EMERGENCY POSTER",
            "Nodplakat": "Emergency poster",
            "Ansvar" :"RESPONSIBILITY",
            "NodplakatText1": "The emergency poster is developed in collaboration with the Joint Rescue centers and emergency services. Kartverket is responsible for the data, ie, place names and maps - as well as the technology.",
            "NodplakatText2": "It is the user's responsibility to verify that it is the correct cabin or location shown on the poster.",
            "NodplakatText3": "Kartverket assumes no responsibility for any errors caused by user, data or technology.",
            "AcceptAndContinue": "ACCEPT AND CONTINUE",
            "GiPunktetNavn": "GIVE YOUR POINT A NAME:",
            "PlaceIs": "THE PLACE IS:",
            "FoundRoadIs": "FOUND ROAD IS",
            "CorrectRoad": "THIS IS CORRECT",
            "Next": "NEXT >",
            "Back": "< BACK",
            "Cancel_txt": "CANCEL",
            "Print": "PRINT",
            "ThematicMap_text" : "THEMATIC MAP",
            "HeightProfile_text": "ELEVATION PROFILE",
            "ChangeTo_text" : "Change to",
            "GoToKartverket_text": "Go to kartverket.no",
            "GiveFeedback_text": "Give feedback",
            "HereYouFind_text": "HERE YOU FIND: ",

            "EU89_Lat_Lon": "EU89 - Geographical degrees (Lat/Lon)",
            "EU89_UTM_31": "EU89, UTM-zone 31",
            "EU89_UTM_32": "EU89, UTM-zone 32",
            "EU89_UTM_33": "EU89, UTM-zone 33",
            "EU89_UTM_34": "EU89, UTM-zone 34",
            "EU89_UTM_35": "EU89, UTM-zone 35",
            "EU89_UTM_36": "EU89, UTM-zone 36",
            "NGO1948_GaussK_1": "NGO1948, Gauss-K. Axis 1",
            "NGO1948_GaussK_2": "NGO1948, Gauss-K. Axis 2",
            "NGO1948_GaussK_3": "NGO1948, Gauss-K. Axis 3",
            "NGO1948_GaussK_4": "NGO1948, Gauss-K. Axis 4",
            "NGO1948_GaussK_5": "NGO1948, Gauss-K. Axis 5",
            "NGO1948_GaussK_6": "NGO1948, Gauss-K. Axis 6",
            "NGO1948_GaussK_7": "NGO1948, Gauss-K. Axis 7",
            "NGO1948_GaussK_8": "NGO1948, Gauss-K. Axis 8",
            "ED50": "ED50 - Geographical degrees",
            "ED50_UTM_31": "ED50, UTM-zone 31",
            "ED50_UTM_32": "ED50, UTM-zone 32",
            "ED50_UTM_33": "ED50, UTM-zone 33",
            "ED50_UTM_34": "ED50, UTM-zone 34",
            "ED50_UTM_35": "ED50, UTM-zone 35",
            "ED50_UTM_36": "ED50, UTM-zone 36",
            "draw_menu": "DRAW AND MEASEURE",
            "iframe_useMarker": "USE MARKER",
            "iframe_shortDesc": "Short description",
            "iframe_longDesc": "Long description",
            "searchResult_roads": "ROADS",
            "searchResult_addresses": "ADDRESSES",
            "searchResult_cadastre": "PROPERTIES",
            "searchResult_placenames": "PLACENAMES",
            "elevationProfile_menu": "ELEVATION PROFILE",
            "searchResult_houseNumber": "Housenumber",
            "houseNr_txt":"House nr.",
            "point_txt": "POINT",
            "line_txt": "LINE",
            "polygon_txt": "POLYGON",
            "text_txt": "TEXT",
            "text_txt_label": "TEXT:",
            "showMeasurements_txt" : "SHOW MEASUREMENTS",
            "showCoordinates_txt" : "SHOW COORDINATES ON THE MAP",
            "pointType_txt": "POINT TYPE:",
            "size_txt": "SIZE:",
            "Small": "S",
            "Medium": "M",
            "Large": "L",
            "color_txt": "COLOR:",
            "snap_txt" : "SNAP",
            "change_txt": "EDIT",
            "remove_txt": "DELETE",
            "save_txt": "SAVE",
            "empty_txt": "EMPTY",
            "lineType_txt": "LINE TYPE:",
            "width_txt": "WIDTH:",
            "opacity_txt": "TRANSPARENCY:",
            "from_text": "FROM KARTVERKET",
            "collapse_txt" : "HIDE",
            "expand_txt" : "SHOW",
            "downloadEmergencyPoster" : "DOWNLOAD",
            "faq_header_txt": "FAQ",
            "drawInMap_txt": "DRAW IN THE MAP",
            "uploadFile_txt": "UPLOAD FILE",
            "profileInfo_txt": "Click in the map and start draw the line.",
            "drawProfile_txt": "DRAW ELEVATION PROFILE",
            "showElevationProfile_txt" : "SHOW ELEVATION PROFILE",
            "chooseFile_txt" : "CHOOSE FILE",
            "shareOnline_txt" : "SHARE ONLINE",
            "embedMap_txt" : "EMBED MAP",
            "facebook_txt" : "FACEBOOK",
            "twitter_txt" : "TWITTER",
            "email_txt" : "SEND AS E-MAIL",
            "copyLink_txt" : "COPY LINK",
            "copy_txt" : "COPY",
            "heading_txt" : "HEADER (OPTIONAL)",
            "description_txt" : "DESCRIPTION (OPTIONAL)",
            "linkToEmbeddedMap_txt": "LINK TO EMBEDDED MAP",
            "download_txt" : "DOWNLOAD",
            "seEiendom_title" : "Eiendom",
            "close_txt" : "CLOSE",
            "showSelection_txt" : "SHOW SELECTION",
            "legend_txt" : "Tegnforklaring",
            "showMoreInformation" : "SHOW MORE INFORMATION"
        }
    });